version: '3.7'

services:
  mysql:
    container_name: pokemon-mysql
    image: pokemon-mysql
    build:
      context: .
      dockerfile: ./dockerfile.mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
     
    networks:
      - PokeNetwork
    ports:
      - 3306:3306
  node:
    depends_on:
      - mysql
    container_name: pokemon-node
    image: pokemon-node
    build:
      context: .
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
    networks:
      - PokeNetwork

networks:
  PokeNetwork: