Drop schema if exists `pokemon`;
Create schema pokemon;
use pokemon;
create table teams(id_team int primary key auto_increment, nome varchar(25));
create table trainer (id_trainer int primary key auto_increment, nome varchar(25));
create table tipo (id_tipo int primary key auto_increment, nome varchar(15));
create table pokemon (id_pokemon int primary key auto_increment, nome varchar(20), tipo1 varchar(15), tipo2 varchar(15));

insert into `teams` (nome) values ("Equipa 1");
insert into `teams` (nome) values ("Equipa 2");
insert into `teams` (nome) values ("Equipa 3");
insert into `teams` (nome) values ("Equipa 4");
insert into `teams` (nome) values ("Equipa 5");
insert into `teams` (nome) values ("Equipa 6");
insert into `teams` (nome) values ("Equipa 7");
insert into `teams` (nome) values ("Equipa 8");
insert into `teams` (nome) values ("Equipa 9");
insert into `teams` (nome) values ("Equipa 10");
insert into `teams` (nome) values ("Equipa 11");
insert into `teams` (nome) values ("Equipa 12");
insert into `teams` (nome) values ("Equipa 13");
insert into `teams` (nome) values ("Equipa 14");
insert into `teams` (nome) values ("Equipa 15");
insert into `teams` (nome) values ("Equipa 16");
insert into `teams` (nome) values ("Equipa 17");
insert into `teams` (nome) values ("Equipa 18");
insert into `teams` (nome) values ("Equipa 19");
insert into `teams` (nome) values ("Equipa 20");
insert into `teams` (nome) values ("Equipa 21");
insert into `teams` (nome) values ("Equipa 22");
insert into `teams` (nome) values ("Equipa 23");
insert into `teams` (nome) values ("Equipa 24");
insert into `teams` (nome) values ("Equipa 25");
insert into `teams` (nome) values ("Equipa 26");
insert into `teams` (nome) values ("Equipa 27");
insert into `teams` (nome) values ("Equipa 28");
insert into `teams` (nome) values ("Equipa 29");
insert into `teams` (nome) values ("Equipa 30");

insert into `trainer`(nome) values ("ASH");
insert into `trainer`(nome) values ("RED");
insert into `trainer`(nome) values ("MISTY");
insert into `trainer`(nome) values ("BROCK");
insert into `trainer`(nome) values ("GARY");
insert into `trainer`(nome) values ("DAWN");
insert into `trainer`(nome) values ("SERENA");
insert into `trainer`(nome) values ("MAY");
insert into `trainer`(nome) values ("IRIS");
insert into `trainer`(nome) values ("TRACEY");
insert into `trainer`(nome) values ("LANCE");
insert into `trainer`(nome) values ("CYNTHIA");
insert into `trainer`(nome) values ("STEVEN");
insert into `trainer`(nome) values ("BLUE");
insert into `trainer`(nome) values ("LEAF");
insert into `trainer`(nome) values ("ALAIN");
insert into `trainer`(nome) values ("GLADION");
insert into `trainer`(nome) values ("N");
insert into `trainer`(nome) values ("LYSANDRE");
insert into `trainer`(nome) values ("LILLIE");
insert into `trainer`(nome) values ("HOP");
insert into `trainer`(nome) values ("MILO");
insert into `trainer`(nome) values ("RAIHAN");
insert into `trainer`(nome) values ("BLAINE");
insert into `trainer`(nome) values ("KOGA");
insert into `trainer`(nome) values ("SABRINA");
insert into `trainer`(nome) values ("ERIKA");
insert into `trainer`(nome) values ("JANINE");
insert into `trainer`(nome) values ("BRUNO");
insert into `trainer`(nome) values ("WALLACE");
insert into `trainer`(nome) values ("FLANNERY");
insert into `trainer`(nome) values ("CLAIR");
insert into `trainer`(nome) values ("AGATHA");

insert into `tipo` (nome) values ("Water");
insert into `tipo` (nome) values ("Fire");
insert into `tipo` (nome) values ("Dark");
insert into `tipo` (nome) values ("Ice");
insert into `tipo` (nome) values ("Steel");
insert into `tipo` (nome) values ("Dragon");
insert into `tipo` (nome) values ("Rock");
insert into `tipo` (nome) values ("Ground");
insert into `tipo` (nome) values ("Grass");
insert into `tipo` (nome) values ("Fighting");
insert into `tipo` (nome) values ("Poison");
insert into `tipo` (nome) values ("Dark");
insert into `tipo` (nome) values ("Fairy");
insert into `tipo` (nome) values ("Ghost");
insert into `tipo` (nome) values ("Electric");
insert into `tipo` (nome) values ("Bug");
insert into `tipo` (nome) values ("Flying");
insert into `tipo` (nome) values ("Fire");
insert into `tipo` (nome) values ("Water");
insert into `tipo` (nome) values ("Normal");
insert into `tipo` (nome) values ("Psychic");
insert into `tipo` (nome) values ("Ice");
insert into `tipo` (nome) values ("Steel");
insert into `tipo` (nome) values ("Dragon");
insert into `tipo` (nome) values ("Rock");
insert into `tipo` (nome) values ("Ground");
insert into `tipo` (nome) values ("Grass");
insert into `tipo` (nome) values ("Fighting");
insert into `tipo` (nome) values ("Poison");
insert into `tipo` (nome) values ("Bug");
insert into `tipo` (nome) values ("Normal");
insert into `tipo` (nome) values ("Psychic");
insert into `tipo` (nome) values ("Ghost");
insert into `tipo` (nome) values ("Poison");
insert into `tipo` (nome) values ("Electric");
insert into `tipo` (nome) values ("Bug");
insert into `tipo` (nome) values ("Normal");
insert into `tipo` (nome) values ("Psychic");
insert into `tipo` (nome) values ("Fairy");
insert into `tipo` (nome) values ("Flying");


insert into `pokemon` (nome, tipo1, tipo2) values ("Charizard", "Fire", "Flying");
insert into `pokemon` (nome, tipo1, tipo2) values ("Pikachu", "Electric", null);
insert into `pokemon` (nome, tipo1, tipo2) values ("Absol", "Dark", null);
insert into `pokemon` (nome, tipo1, tipo2) values ("Vaporean", "Water", null);
insert into `pokemon` (nome, tipo1, tipo2) values ("Deoxys", "Psychic", null);
insert into `pokemon` (nome, tipo1, tipo2) values ("Jigglypuff", "Normal", "Fairy");
insert into `pokemon` (nome, tipo1, tipo2) values ("Snorlax", "Normal", null);
insert into `pokemon` (nome, tipo1, tipo2) values ("Gengar", "Poison", "Ghost");
insert into `pokemon` (nome, tipo1, tipo2) values ("Shedinja", "Bug", "Ghost");
insert into `pokemon` (nome, tipo1, tipo2) values ("Bulbasaur", "Grass", "Poison");
insert into `pokemon` (nome, tipo1, tipo2) values ("Charmander", "Fire", null);
insert into `pokemon` (nome, tipo1, tipo2) values ("Squirtle", "Water", null);
insert into `pokemon` (nome, tipo1, tipo2) values ("Pidgeotto", "Normal", "Flying");
insert into `pokemon` (nome, tipo1, tipo2) values ("Sandshrew", "Ground", null);
insert into `pokemon` (nome, tipo1, tipo2) values ("Zubat", "Poison", "Flying");
insert into `pokemon` (nome, tipo1, tipo2) values ("Oddish", "Grass", "Poison");
insert into `pokemon` (nome, tipo1, tipo2) values ("Meowth", "Normal", null);
insert into `pokemon` (nome, tipo1, tipo2) values ("Machamp", "Fighting", null);
insert into `pokemon` (nome, tipo1, tipo2) values ("Magnemite", "Electric", "Steel");
insert into `pokemon` (nome, tipo1, tipo2) values ("Onix", "Rock", "Ground");
insert into `pokemon` (nome, tipo1, tipo2) values ("Cubone", "Ground", null);
insert into `pokemon` (nome, tipo1, tipo2) values ("Hitmonlee", "Fighting", null);
insert into `pokemon` (nome, tipo1, tipo2) values ("Jynx", "Ice", "Psychic");
insert into `pokemon` (nome, tipo1, tipo2) values ("Mew", "Psychic", null);
insert into `pokemon` (nome, tipo1, tipo2) values ("Eevee", "Normal", null);
insert into `pokemon` (nome, tipo1, tipo2) values ("Ditto", "Normal", null);
insert into `pokemon` (nome, tipo1, tipo2) values ("Togepi", "Fairy", null);
insert into `pokemon` (nome, tipo1, tipo2) values ("Houndoom", "Dark", "Fire");
insert into `pokemon` (nome, tipo1, tipo2) values ("Lugia", "Psychic", "Flying");
insert into `pokemon` (nome, tipo1, tipo2) values ("Rayquaza", "Dragon", "Flying");
insert into `pokemon` (nome, tipo1, tipo2) values ("Torterra", "Grass", "Ground");
insert into `pokemon` (nome, tipo1, tipo2) values ("Piplup", "Water", null);
insert into `pokemon` (nome, tipo1, tipo2) values ("Luxray", "Electric", null);
insert into `pokemon` (nome, tipo1, tipo2) values ("Garchomp", "Dragon", "Ground");
insert into `pokemon` (nome, tipo1, tipo2) values ("Lucario", "Fighting", "Steel");
insert into `pokemon` (nome, tipo1, tipo2) values ("Weavile", "Dark", "Ice");
insert into `pokemon` (nome, tipo1, tipo2) values ("Gallade", "Psychic", "Fighting");
insert into `pokemon` (nome, tipo1, tipo2) values ("Arceus", "Normal", null);
insert into `pokemon` (nome, tipo1, tipo2) values ("Greninja", "Water", "Dark");

GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '12345678'

